#SERVER CONFIG
server:
  port: 8085
  
#SPRING CONFIG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/backendpro?useSSL=false
    username: root
    password: psalguero
  
  thymeleaf:
    cache: false
  
  #JPA CONFIG
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.improvedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect